Repository WGBH-MLA/ov-wag, pull requests merged in 2023-12, with the labels that each got.

#132 🔏 OAuth
  ov_wag/settings/base.py
  ov_wag/templates/socialaccount/authentication_error.html
  ov_wag/templates/wagtailadmin/login.html
  ov_wag/templatetags/__init__.py
  ov_wag/templatetags/custom_tags.py
  ov_wag/urls.py
  pdm.lock
  pyproject.toml
Labels: enhancement ➕

#138 💿 AAPB records
  ov_collections/blocks.py
  ov_collections/migrations/0010_collection_aapb_records_alter_collection_content.py
  ov_collections/migrations/0011_alter_collection_aapb_records_and_more.py
  ov_collections/models.py
Labels: enhancement ➕

#140 🪓 Fixes Auth0 login
  ov_wag/templates/wagtailadmin/login.html
Labels: bug 🐛

#131 📗 Backend Docs
  docs/dev.md
  docs/reference/index.md
  docs/setup.md
  docs/style/cmd.css
  mkdocs.yml
Labels: documentation 📜, CI 🦾, CD 🏗️, dev 💻

#141 🥣 `other_exhibits` serializer
  authors/models.py
  exhibits/models.py
Labels: enhancement ➕

#143 📣 Featured Exhibits
  exhibits/api.py
  exhibits/migrations/0005_exhibitpage_featured.py
  exhibits/models.py
  ov_wag/api.py
Labels: enhancement ➕

#144 🎞 AAPB Record
  ov_collections/blocks.py
  ov_collections/migrations/0012_remove_collection_aapb_records_and_more.py
  ov_collections/models.py
Labels: enhancement ➕, breaking 💔
