Repository WGBH-MLA/ov-wag, pull requests merged in 2023-11, with the labels that each got.

#78 📬 PDM
  .gitignore
  pdm.lock
  pdm.toml
  pyproject.toml
Labels: maintenance 🔧, breaking 💔

#76 🎬 Workflow Actions
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/update.yml
  dev.yml
  docker-compose.yml
  ov
  test.yml
Labels: CI 🦾, CD 🏗️, maintenance 🔧

#85 🕸 VSCode Debugger
  .env.example
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  dev.yml
  docker-compose.yml
  manage.py
  ov_wag/settings/base.py
  ov_wag/settings/dev.py
  ov_wag/settings/production.py
  ov_wag/tests/test_api.py
  ov_wag/tests/test_env.py
  pdm.lock
  pyproject.toml
  requirements.txt
Labels: enhancement ➕, maintenance 🔧

#93 ⬛ Black
  exhibits/management/commands/rename.py
  exhibits/models.py
  exhibits/tests/factories.py
  exhibits/tests/test_exhibit_page.py
  home/models.py
  ov_wag/urls.py
  pyproject.toml
  search/views.py
Labels: maintenance 🔧

#94 👖 Lint
  authors/models.py
  authors/serializers.py
  authors/views.py
  exhibits/admin.py
  exhibits/management/commands/rename.py
  exhibits/models.py
  exhibits/views.py
  home/models.py
  ov_collections/admin.py
  ov_collections/models.py
  ov_collections/tests.py
  ov_collections/views.py
  ov_wag/settings/base.py
  ov_wag/settings/dev.py
  ov_wag/settings/production.py
  ov_wag/tests/test_api.py
  ov_wag/tests/test_env.py
  ov_wag/urls.py
  pdm.lock
  pyproject.toml
Labels: maintenance 🔧

#97 🧫 Pytest
  .github/workflows/CI.yml
  .github/workflows/test-coverage.yml
  conftest.py
  ov_wag/settings/base.py
  ov_wag/settings/test.py
  ov_wag/tests/test_env.py
  pdm.lock
  pyproject.toml
Labels: CI 🦾, maintenance 🔧

#83 💻 CLI
  Dockerfile
  cli/__init__.py
  cli/cli.py
  cli/utils.py
  docker-compose.yml
  ov
  ov_wag/__init__.py
  ov_wag/_version.py
  pdm.lock
  pyproject.toml
  test.yml
Labels: enhancement ➕, maintenance 🔧

#96 🛡 GGShield
  .pre-commit-config.yaml
  README.md
Labels: maintenance 🔧

#100 🏷 Labels
  .github/release.yml
  .github/workflows/labels.yml
Labels: maintenance 🔧

#98 🐩 Upgrade Wagtail
  authors/admin.py
  authors/migrations/0001_initial.py
  authors/models.py
  cli/utils.py
  codecov.yml
  exhibits/migrations/0001_initial.py
  exhibits/models.py
  home/migrations/0003_homepage_body.py
  home/models.py
  ov_collections/blocks.py
  ov_collections/models.py
  ov_wag/_version.py
  ov_wag/serializers.py
  ov_wag/settings/base.py
  ov_wag/tests/test_api.py
  ov_wag/urls.py
  pdm.lock
  pyproject.toml
  pytest.ini
  search/views.py
Labels: maintenance 🔧, breaking 💔

#101 🎭 Production image
  Dockerfile
  dev.yml
  docker-compose.yml
  docker_entrypoints/deploy.sh
  docker_entrypoints/dev.sh
  ov_wag/settings/production.py
  pdm.lock
  pyproject.toml
Labels: bug 🐛, CD 🏗️

#115 👁 Preview
  .env.example
  client/index.html
  exhibits/models.py
  home/models.py
  ov_collections/models.py
  ov_wag/api.py
  ov_wag/settings/base.py
  pdm.lock
  pyproject.toml
Labels: enhancement ➕

#137 🇮🇹 Italic Titles
  ov_collections/blocks.py
  ov_collections/migrations/0010_alter_collection_content.py
Labels: enhancement ➕
